# version: "3.8"

# services:
#   ollama:
#     image: ollama/ollama:latest
#     container_name: ollama
#     ports:
#       - "11434:11434"
#     volumes:
#       - ollama-data:/root/.ollama

#   backend:
#     build: .
#     container_name: chatbot-backend
#     ports:
#       - "5001:5001"
#     depends_on:
#       - ollama
#     environment:
#       - OLLAMA_HOST=http://ollama:11434

# volumes:
#   ollama-data:






version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

  backend:
    build: .
    container_name: chatbot-backend
    ports:
      - "5001:5001"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3001:3000"
    volumes:
      - open-webui-data:/app/backend/data
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
    depends_on:
      - ollama

volumes:
  ollama-data:
  open-webui-data:
